modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="${mod_license}" # Or "MIT", "Apache-2.0", etc.

[[mods]] #mandatory
modId="${mod_id}" #mandatory -- Use your actual modId here, lowercase, no spaces
version="${mod_version}" #mandatory -- Your mod's version
displayName="${mod_name}" #mandatory -- Your mod's display name

clazz="com.smeltingmetal.SmeltingMetalMod"
authors="${mod_authors}" #optional

description='''${mod_description}'''

[[dependencies.smeltingmetal]]
modId="forge" #mandatory
mandatory=true #mandatory
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"
[[dependencies.smeltingmetal]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.smeltingmetal]]
modId="create"
mandatory=false
versionRange="[0,)"
ordering="AFTER"
side="BOTH"
