# Smelting Metal Mod - Metals Configuration
#
# Format: "modid:metal_id=ingot_modid:ingot_id"
# Example: "minecraft:iron=minecraft:iron_ingot"
# Add one metal definition per line

[metals]
# List of metal definitions in format: modid:metal_id=ingot_modid:ingot_id
metal_definitions = [
    "minecraft:iron=minecraft:iron_ingot",
    "minecraft:gold=minecraft:gold_ingot",
    "minecraft:copper=minecraft:copper_ingot"
]
